use_frameworks!

target 'SCKeychainManager_Example' do
  pod 'SCKeychainManager', :path => '../'

  target 'SCKeychainManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
