use_frameworks!
platform :ios, '10.0'
target 'SCKeychainManager_Example' do
  pod 'SCKeychainManager', :path => '../'
  
  target 'SCKeychainManager_Tests' do
    inherit! :search_paths
 
    pod 'Quick'
    pod 'Nimble'
    pod 'SCPKIHelper'
  end
end
